### PR TITLE
Various cleanup

### PR DESCRIPTION
**Pull request by joegoldman2**
Mainly:
- Remove trailing spaces
- Add missing carriage return at the end of some files
- Re-encode some files to comply with the encoding defined in the .editorconfig

### CODE REVIEW

**Comment by joegoldman2** [comment]
@abergs this PR is ready to be reviewed.

**Comment by iamcarbon** [comment]
Everything looks good to me.

**Review by abergs — COMMENTED** [review]
Thanks, looks great!

**Review by abergs — APPROVED** [review]
Thanks, looks great!

**Pull request merged**
