### PR TITLE
Enable C# 11 and embed base64 encoded certificates as UTF-8 data

### PR DESCRIPTION
**Pull request by iamcarbon**
Is a bit faster to parse UTF-8 data directly than convert from UTF-16. 

NOTE, this uses the built-in support for static data initialization. Accessing ROOT_CERT is non-allocating and refers directly to the data.

This PR also simplifies a check using C# 11 list patterns.

### CODE REVIEW

**Comment by iamcarbon** [comment]
Ahh, CI doesn't like C# 11. I'll look into this a bit later.

**Comment by iamcarbon** [comment]
future note: We should also consider cross-targeting and testing against net8.0 after the next preview. This will also provide us with the latest System.Text.Json source generation improvements.

**Comment by iamcarbon** [comment]
@abergs Ready for review.

**Review by abergs — APPROVED** [review]
Looks good, thank you @iamcarbon

**Pull request merged**
