### PR TITLE
use coerceToArrayBuffer to post-process assertion options in Demo js

### PR DESCRIPTION
**Pull request by dradovic**
Just did the todos from the comments.

### CODE REVIEW

**Comment by dradovic** [comment]
@dotnet-policy-service agree

**Comment by dradovic** [comment]
Note that there's a subtle change here: by using `coerceToArrayBuffer` the bytes are copied in a for-loop instead of using `Uint8Array.from`.

**Review by abergs — APPROVED** [review]

**Comment by abergs** [comment]
Long time coming but let's merge this now :)

**Comment by abergs** [comment]
Thanks @dradovic!

**Pull request merged**
