### PR TITLE
Improve Code Quality

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR:

- Consolidates the X509Certificate constructor / error handlers in X509CertificateHelper. We now throw an improved error message if there was invalid Base64 data.
- Uses the built-in JSON converter to decode base64 data. System.Text.Json can convert directly from the utf-8 bytes using the vectorized Base64 converter.
- Replaces the BinaryWriter with BufferWriter

### CODE REVIEW

**Review by aseigler — APPROVED** [review]

**Comment by iamcarbon** [comment]
@abergs Quick ping for a review.

**Review by abergs — APPROVED** [review]
Sorry that this took time, looks good!

**Comment by abergs** [comment]
However tests are failing, while master is green.

Would you like to investigare @iamcarbon?

**Comment by aseigler** [comment]
> However tests are failing, while master is green.
> 
> Would you like to investigare @iamcarbon?

It's because I fixed the errors in a PR submitted after this one.

**Comment by iamcarbon** [comment]
@abergs @aseigler merged in the test fixes from Alex. We're green!

**Pull request merged**
