### PR TITLE
Add .Net 6 as supported framework

### PR DESCRIPTION
**Pull request by trejjam**
Hi, there is already the .Net6 framework.
I prepared this small PR that adds it right next to the .Net5.

I found (and [resolved](https://github.com/trejjam/fido2-net-lib/commit/079b2e38f17cdab8be488e1f97c241d6681470e2)) one deprecation in packages: https://github.com/aspnet/Announcements/issues/303

### CODE REVIEW

**Comment by trejjam** [comment]
Do you mind if I add the PR check pipeline here to the Github Actions?

**Comment by trejjam** [comment]
Hi, I think you are doing a lot of duplicity work in the pipelines. E.g. the prepare runtime is useless, since the next stages do a new checkout and as you can see the buld do a new restore.

Do you mind if I simplify it?

**Comment by aseigler** [comment]
Go for it!

**Comment by trejjam** [comment]
It should be ready

**Comment by trejjam** [comment]
The pipeline time is now around half of the baseline.

**Comment by aseigler** [comment]
Thanks!

**Pull request merged**
