### PR TITLE
Update System.IdentityModel.Tokens.Jwt and xunit

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR updates the following dependencies:

- System.IdentityModel.Tokens.Jwt -> v7.0.2
- xunit -> 2.5.1.
- Microsoft.NET.Test.Sdk -> 17.7.2

And reacts to the following breaking changes:

System.IdentityModel.Tokens.Jwt v7.0.2 no longer serializes byte arrays as base64 strings. When generating tokens for testing, we need to base64 encode manually. In the main library, we only validate tokens... so we are OK.

xunit 2.5.1 has an updated analyzer that require async method calls to occur in an async context. The tests have been updated accordingly.

### CODE REVIEW

**Comment by iamcarbon** [comment]
@abergs Ready for review.

**Comment by iamcarbon** [comment]
If we get this merged in, I'd like to take a look at migrating to Microsoft.IdentityModel.JsonWebTokens as well. This would require that AttestationVerifier.Verify by changed to AttestationVerifier.VerifyAsync.

**Comment by aseigler** [comment]
This looks good to me!

**Review by aseigler — APPROVED** [review]

**Comment by iamcarbon** [comment]
@abergs Let me know if there's anything left on this one.

**Review by joegoldman2 — APPROVED** [review]
Looks good to me.

**Pull request merged**
