### PR TITLE
Simplify enum mapping & update specification links

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR:

- Removes support for enforcing the case sensitivity of the Enum parser. Enum parsing has always been case insensitive in the library.

- Update various references to a draft webauthn specification to the final published specification.

### CODE REVIEW

**Comment by iamcarbon** [comment]
@aseigler @abergs Ready for review.

**Review by abergs — APPROVED** [review]
Thank you Jason, this looks good!

**Comment by iamcarbon** [comment]
@abergs Let me know if there's anything else here before we merge.

**Comment by iamcarbon** [comment]
@abergs Let me know if this is good to merge.

**Pull request merged**
