### PR TITLE
Add CTAP support

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR implements the basic CTAP2 protocol models used to interact directly with a Fido Authenticator Device.

It has basic test coverage, but should be considered a WIP until a concrete implementation has been implemented and we have test coverage across all the models.

Device & platform specific implementations would be built on-top of this API to support USB, Bluetooth, NFT, and local FIDO devices.

We should also consider building a higher level API that accept concrete key objects, raw pins, and .NET specific naming conventions.

An example FIDO2 authenticator implementation:

``` csharp
public HidFidoAuthenticator : FidoAuthenticator 
{
   private readonly IHumanInterfaceDevice _hid;
  
   public HidFidoAuthenticator(IHumanInterfaceDevice hid) {
      _hid = hid;
   } 
   
   protected override ValueTask<FidoAuthenticatorResponse> ExecuteCommandAsync(CtapCommand command) {
         var payload = command.GetPayload();
         
         // Send command over USB w/ appropriate framing
         
         await hid.SendAsync(payload, timeout: 5000);
         
         var responseData = await _hid.ReadData(timeout: 5000);
         
         return new FidoAuthenticatorResponse(responseData);
  }
}
```

### CODE REVIEW

**Comment by iamcarbon** [comment]
@aseigler Ready for early review / feedback.

Would you be interested in help building the next round of higher level APIs together?

**Comment by aseigler** [comment]
This is one part that I intended to build into the project much earlier on but never got around to it.  I don't see any reason not to include this, as long as @abergs is on board I am good with this addition.

**Review by aseigler — APPROVED** [review]

**Comment by abergs** [comment]
@iamcarbon This is a great contribution! Impressive work. I do however think it would benefit from having some more documentation, e.g. a readme. We want to make sure developers can understand what the CTAP2 API's are for, and how they could use them.

**Review by abergs — APPROVED** [review]
I think this contribution is great. Neatly structured and well written. Since I don't know much about the CTAP2 API, I can't comment on the functionality.

I think a great next step would be to add some more documentation. I think in a form of a a readme.md in the Fido2.Ctap2 that explains scope and some examples of basic usage.

**Comment by abergs** [comment]
@iamcarbon I'm ready to merge this when conflicts are resolved. It's an easy conflict but I'd prefer if you rebase your branch on master so that history is kept clean (git rebase master).

If you don't have time I'll do it but I would have to open a new PR since I don't have permissions on your fork.

**Comment by iamcarbon** [comment]
@abergs conflicts resolved. thanks!

**Comment by abergs** [comment]
Great contribution. Merged.

**Pull request merged**
