### PR TITLE
Review lifecycle of services registered in the DI container

### LINKED ISSUE #439: Review lifecycle of services registered in the DI container
Currently `IMetadataService` is registered as a scoped service:

https://github.com/passwordless-lib/fido2-net-lib/blob/15263ca8bc4ceea84c3ef287300ac2962d9afe10/Src/Fido2.AspNet/Fido2NetLibBuilderExtensions.cs#L90

But `IFido2` and `IMetadataRepository` are registered as transient:

https://github.com/passwordless-lib/fido2-net-lib/blob/15263ca8bc4ceea84c3ef287300ac2962d9afe10/Src/Fido2.AspNet/Fido2NetLibBuilderExtensions.cs#L29

https://github.com/passwordless-lib/fido2-net-lib/blob/15263ca8bc4ceea84c3ef287300ac2962d9afe10/Src/Fido2.AspNet/Fido2NetLibBuilderExtensions.cs#L83

I think it makes sense to register `IFido2` and `IMetadataRepository` as scoped as well here.

What do you think @abergs and @iamcarbon?

### PR DESCRIPTION
**Pull request by joegoldman2**
Fixes #439.

### CODE REVIEW

**Comment by joegoldman2** [comment]
@abergs @aseigler this PR is ready to be reviewed.

**Comment by abergs** [comment]
I would need to think about what side effect this change could have before this is merged.

**Comment by joegoldman2** [comment]
@iamcarbon @aseigler any opinions ?

**Comment by joegoldman2** [comment]
@iamcarbon any opinions?

**Comment by abergs** [comment]
@iamcarbon Happy to hear if you have any thoughts

**Comment by joegoldman2** [comment]
He gave his thoughts here: https://github.com/passwordless-lib/fido2-net-lib/issues/439#issuecomment-1888116751

**Comment by iamcarbon** [comment]
Looks good. 👍

**Review by abergs — APPROVED** [review]

**Comment by abergs** [comment]
Thank you @joegoldman2 👍 Happy friday.

**Pull request merged**
