### PR TITLE
Improve Code Quality

### PR DESCRIPTION
**Pull request by iamcarbon**
- Enables C#9
- Eliminates several allocations
- Compares strings using invariant culture
- Simplifies null comparisions
- Add missing Async suffixes
- Seals various internal classes (improves codegen)
- Enables nullable
- [Breaking] Construct ParsedAttestationObject via constructor to fix nullability warnings
- [Breaking] Construct TokenBindingDto via constructor to fix nullability warnings
- Optimize Base64 encoder / decoder

### CODE REVIEW

**Comment by iamcarbon** [comment]
@aseigler ping. let me know your thoughts on these improvements before I get too carried away.

**Comment by iamcarbon** [comment]
@aseigler Reverted the changes to the externallibs and squeezed in a few more optimizations.

This is ready for final review / consideration for merging. I plan to start a PR to migrate to System.Text.Json after this. It looks like we got pretty close before.

**Comment by aseigler** [comment]
> @aseigler Reverted the changes to the externallibs 

AsnElt.cs still has a couple of (trivial) changes

**Comment by iamcarbon** [comment]
Updated.

**Comment by iamcarbon** [comment]
Let me know if things look good, and I'll start a second followup PR for the next round of improvements.

**Pull request merged**
